// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	序号      *string `gorm:"column:序号" json:"序号"`
	客户姓名    *string `gorm:"column:客户姓名" json:"客户姓名"`
	国家码     *string `gorm:"column:国家码" json:"国家码"`
	手机号     *string `gorm:"column:手机号" json:"手机号"`
	备注名     *string `gorm:"column:备注名" json:"备注名"`
	性别      *string `gorm:"column:性别" json:"性别"`
	生日      *string `gorm:"column:生日" json:"生日"`
	年龄      *string `gorm:"column:年龄" json:"年龄"`
	客户编号    *string `gorm:"column:客户编号" json:"客户编号"`
	成为客户时间  *string `gorm:"column:成为客户时间" json:"成为客户时间"`
	客户身份    *string `gorm:"column:客户身份" json:"客户身份"`
	成为会员时间  *string `gorm:"column:成为会员时间" json:"成为会员时间"`
	归属门店    *string `gorm:"column:归属门店" json:"归属门店"`
	营销顾问    *string `gorm:"column:营销顾问" json:"营销顾问"`
	客户来源    *string `gorm:"column:客户来源" json:"客户来源"`
	推广员     *string `gorm:"column:推广员" json:"推广员"`
	推广员手机号  *string `gorm:"column:推广员手机号" json:"推广员手机号"`
	绑定时间    *string `gorm:"column:绑定时间" json:"绑定时间"`
	客户标签    *string `gorm:"column:客户标签" json:"客户标签"`
	备注      *string `gorm:"column:备注" json:"备注"`
	首次消费时间  *string `gorm:"column:首次消费时间" json:"首次消费时间"`
	上次消费时间  *string `gorm:"column:上次消费时间" json:"上次消费时间"`
	累计消费频次  *string `gorm:"column:累计消费频次" json:"累计消费频次"`
	累计消费金额  *string `gorm:"column:累计消费金额" json:"累计消费金额"`
	客单价     *string `gorm:"column:客单价" json:"客单价"`
	可用积分    *string `gorm:"column:可用积分" json:"可用积分"`
	有效持卡张数  *string `gorm:"column:有效持卡张数" json:"有效持卡张数"`
	本金剩余金额  *string `gorm:"column:本金剩余金额" json:"本金剩余金额"`
	赠额剩余金额  *string `gorm:"column:赠额剩余金额" json:"赠额剩余金额"`
	次卡剩余金额  *string `gorm:"column:次卡剩余金额" json:"次卡剩余金额"`
	次卡剩余次数  *string `gorm:"column:次卡剩余次数" json:"次卡剩余次数"`
	卡赠送剩余次数 *string `gorm:"column:卡赠送剩余次数" json:"卡赠送剩余次数"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
