// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOldCustomerWhitelist = "old_customer_whitelist"

// OldCustomerWhitelist mapped from table <old_customer_whitelist>
type OldCustomerWhitelist struct {
	商品名称 *string `gorm:"column:商品名称" json:"商品名称"`
}

// TableName OldCustomerWhitelist's table name
func (*OldCustomerWhitelist) TableName() string {
	return TableNameOldCustomerWhitelist
}
