// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	商品名称  *string `gorm:"column:商品名称" json:"商品名称"`
	课时费   *string `gorm:"column:课时费" json:"课时费"`
	固定课时费 *string `gorm:"column:固定课时费;comment:优先使用固定课时费，没值的情况，按照新老客，取课时费字段计算" json:"固定课时费"` // 优先使用固定课时费，没值的情况，按照新老客，取课时费字段计算
	课时    *string `gorm:"column:课时" json:"课时"`
	开卡率   *string `gorm:"column:开卡率" json:"开卡率"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
